[package]
name = "abstract-astroport-adapter"
version = "2.10.0"
authors = ["Abstract Money <contact@abstract.money>"]
edition = "2021"
description = "Abstract DexCommand implementation for Astroport"
license = "Apache-2.0"
repository = "https://github.com/astroport-fi/astroport"

[features]
default=["full_integration"]
local=[]
full_integration=["dep:cw20","dep:cosmwasm-schema", "dep:cw-asset", "dep:cw-utils","dep:astroport"]

[dependencies]
cosmwasm-std = { version = "1.1" }
abstract-dex-adapter-traits = {git="https://github.com/AbstractSDK/adapters", branch="feature/impl-in-origin-repo"}
abstract-staking-adapter-traits = {git="https://github.com/AbstractSDK/adapters", branch="feature/impl-in-origin-repo"}
abstract-sdk = { version="0.16.1"}



cw20 = { version = "0.15" , optional=true}
cosmwasm-schema = {version="1.1", optional=true}
cw-asset = {version="3.0.0", optional=true}
cw-utils = {version="1.0.1", optional=true}

astroport = {path="../astroport/", optional=true}
